# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b90a19139aae16ae87946bd88ad1d8292291ce16946aaff4be46254db7cca9cbba11bd9213b74efa05b02c663c4e887e87e3161202e0f7787153b935b0cec82

test:
  secret_key_base: dab1b4577d43d7c2e66422fee4ead539a564b330425c466b5e607a1b80fc884d0099df8808a06020a4252fa95a56d661e7731fc7f6dd614f822588658d23ed10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
