# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a2e10b90385f3db0898c1cb3dd345ba8278a0e57e4dee19c65c24179d36a6b44746606792d88323a833d0de42367097f4fa5af4f81f5803cdf35aa684b02df9

test:
  secret_key_base: 387e9f93521d66fd95dc5dad2a71f43f474dfa76cd6777d5207d91462479b48f2d14525d05dd39258e83c3987597ef255efcd27017173cb01fcd43c7f3ded06e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
