# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b4f6b2f50d43a972d5ebdf55bae9f5c9d1611c7d4d924926a51649b9be188eb9d053e8a82f3e84d6ab26bd6aff4dde0d8463dc65dec3e1537b91107e26ebdc4

test:
  secret_key_base: d454d3e7da9223d98c53edba04a22e8a5c52f4d882e21de8071589ff9851ee671438297032d67c22cbf54059ca8b613b62eb75707cc926eef763af786f8e1aff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
